# Public Servers
[public_servers]
public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.239.78.102
public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.201.186.26
public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=54.87.154.99
public_server_4 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=52.71.233.204
public_server_5 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=100.26.255.81

# Private Servers
[private_servers]
private_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=10.0.13.150
private_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=10.0.15.139
