- name: Users creation
  hosts: Role_dev
  gather_facts: true
  become: yes
  vars:
    group_list:
      - modelchange
      - investigation
    users:
      - { name: "vinitha", groups: ["modelchange"], password: "{{ 'Vinitha@123' | password_hash('sha512') }}" }
      #sudo apt install python3-passlib -y ( for password_hash filter it is required)
      - { name: "sravan", groups: ["modelchange"], password: "{{ 'Sravan@123' | password_hash('sha512') }}" }
      - { name: "bhadra", groups: ["investigation"], password: "{{ 'Bhadra@123' | password_hash('sha512') }}" }
      - { name: "naga", groups: ["investigation"], password: "{{ 'Naga@123' | password_hash('sha512') }}" }
  tasks:
    - name: Creating groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ group_list }}"
    - name: Creating users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"
      no_log: true
    - name: Add SSH public key for users
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', 'devuser.pub') }}"
      loop: "{{ users }}"
      no_log: true
    - name: checking group status
      shell:
        cat /etc/group | grep "{{ item }}"
      register: group_status
      loop: "{{ group_list }}"
    - name: checking user status
      shell:
        id {{ item.name }}
      register: user_status
      loop: "{{ users }}"
      no_log: true