# Ansible Controller Main Servers
[ansible_controller_public_servers]
ansible_controller_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=13.222.103.249

# Dev Servers
[dev_public_servers]
dev_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.202.210.249
dev_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=35.171.20.117
dev_public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=52.91.197.103

# Test Servers
[test_public_servers]
test_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.197.183.76
test_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.93.3.74
test_public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=54.226.182.67

# QA Servers
[qa_public_servers]
qa_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.210.183.253
qa_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=184.72.126.249
qa_public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.94.192.218

[all_public_servers:children]
dev_public_servers
qa_public_servers
test_public_servers

# Public Servers
[public_servers]
public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=13.222.103.249
public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.202.210.249
public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=35.171.20.117
public_server_4 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=52.91.197.103
public_server_5 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.197.183.76
public_server_6 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.93.3.74
public_server_7 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=54.226.182.67
public_server_8 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.210.183.253
public_server_9 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=184.72.126.249
public_server_10 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.94.192.218

# Private Servers
[private_servers]

