# Ansible Controller Main Servers
[ansible_controller_public_servers]
ansible_controller_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.231.158.88

# Dev Servers
[dev_public_servers]
dev_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=13.218.194.202
dev_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=18.212.5.136

# Test Servers
[test_public_servers]
test_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.231.165.86
test_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=13.220.210.101

# QA Servers
[qa_public_servers]
qa_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.236.152.170
qa_public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.82.198.147

[all_public_servers:children]
dev_public_servers
qa_public_servers
test_public_servers

# Public Servers
[public_servers]
public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.231.158.88
public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=13.218.194.202
public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=18.212.5.136
public_server_4 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.231.165.86
public_server_5 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=13.220.210.101
public_server_6 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.236.152.170
public_server_7 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.82.198.147
 
# Private Servers
[private_servers]


