# Ansible Controller Main Servers
[ansible_controller_public_servers]
ansible_controller_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.228.8.91

# Dev Servers
[dev_public_servers]

# Test Servers
[test_public_servers]

# QA Servers
[qa_public_servers]

[all_public_servers:children]
dev_public_servers
qa_public_servers
test_public_servers

# Public Servers
 [public_servers]
  public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519_glpskumar ansible_host=3.228.8.91
 
# Private Servers
[private_servers]


