# Ansible Controller Main Servers
[ansible_controller_public_servers]
ansible_controller_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.193.198.173

# Dev Servers
[dev_public_servers]
dev_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.91.53.204

# Test Servers
[test_public_servers]
test_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=98.80.204.140

# QA Servers
[qa_public_servers]
qa_public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.231.22.204

[all_public_servers:children]
dev_public_servers
qa_public_servers
test_public_servers

# Public Servers
[public_servers]
public_server_1 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=44.193.198.173
public_server_2 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.91.53.204
public_server_3 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=98.80.204.140
public_server_4 ansible_port=22 ansible_user=ubuntu ansible_ssh_private_key_file=glpskey ansible_host=3.231.22.204

# Private Servers
[private_servers]


